### ISSUE TITLE
7, 8, and 'xah-end-of-line-or-block problems when using in iTerm2, MacBook Air 2015

### ISSUE THREAD

**Issue by antonshwab** [xahlee/xah-fly-keys#12] opened 2017-01-26 11:41 UTC
I use emacsclient -t in iTerm2. And have next problems with qwerty version:

1) 7 and 8 still don't work. In *message* buffer i see `delete-window: Attempt to delete minibuffer or sole ordinary window`
2) `'xah-end-of-line-or-block` prints";" instead move to end of line/block. But in *message* buffer, for example, `'xah-end-of-line-or-block` works fine.
3) How I can copy/paste in OS from iTerm2 emacsclient -t?

my emacs version is 25.1 from https://emacsformacosx.com/. 

[my current init.el](https://gist.github.com/antonshwab/d6c2d704e6c811ec88a3b419c1a548ae)

**Comment by xahlee** [comment] 2017-01-26 12:20
qwerty key 7 8 are now fixed. my bad.

**Comment by xahlee** [comment] 2017-01-26 12:23
for problem 2,
when this happens, 
M-x describe-key then type the semicolon.
What command does it show? 

also,
what is your current major mode?
M-x describe-variable then type major-mode.

**Comment by xahlee** [comment] 2017-01-26 12:31
for problem 3, am not quite sure i know what you mean exactly.

copy/paste between emacs and OS should work or not work regardless of xah fly keys mode.

I haven't used Mac for few years, but normally Cmd+c would do, and in emacs you can paste by emacs usual yank.But i've heard problems where you have to do some config to get that to work (but this problem never happened to me). but i don't have a Mac now.

**Comment by xahlee** [comment] 2017-01-26 12:35
for problem 2, in your init, put the layout before turning on mode, like this:

    (use-package xah-fly-keys
      :ensure t
      :config
      (xah-fly-set-layout "qwerty")
      (xah-fly-keys 1)
      (global-set-key (kbd "C-i") 'xah-fly-command-mode-activate)
      )

i also fixed it in my doc. Thanks.

**Comment by antonshwab** [comment] 2017-01-26 19:26
Problem 1 is solved. Thank you!

But 2 not:

- M-x describe-variable then type major-mode. 

```
major-mode is a variable defined in ‘C source code’.
Its value is ‘lisp-interaction-mode’
Original value was fundamental-mode
Local in buffer *scratch*; global value is fundamental-mode

  Automatically becomes buffer-local when set.

Documentation:
Symbol for current buffer’s major mode.
The default value (normally ‘fundamental-mode’) affects new buffers.
A value of nil means to use the current buffer’s major mode, provided
it is not marked as "special".

You can customize this variable.

[back]
```
- M-x describe-key then type the semicolon.

```
; runs the command xah-end-of-line-or-block (found in
  xah-fly-key-map), which is an interactive compiled Lisp function in
  ‘xah-fly-keys.el’.

It is bound to ;.

(xah-end-of-line-or-block)

Move cursor to end of line, or end of current or next text block.

• When called first time, move cursor to end of line.
• When called again, move cursor to end of paragraph.
• When called again, move cursor to end of next paragraph.

URL ‘http://ergoemacs.org/emacs/emacs_keybinding_design_beginning-of-line-or-block.html’
Version 2017-01-17

[back]
```

**Comment by xahlee** [comment] 2017-01-26 21:04
i can't reproduce problem 2.

from your report, the semicolon key is calling the right command xah-end-of-line-or-block. This means, there's no problem in the qwerty/dvorak translation.

and looking at the command xah-end-of-line-or-block, it's impossible for it to insert a character.

also, looking at your current mode, it's *scratch* buffer. So, that should remove possibility of some mode playing with keys.

i tried restart my emacs GNU Emacs 25.1.1 with init just xah fly keys and set to qwerty, and tried scratch buffer. Can't reproduce it.


--------------------------------------------

Try put just this in your init:

    (add-to-list 'load-path "~/git/xah-fly-keys/") // change to your path
    (require 'xah-fly-keys)
    
    (progn
        (setq xah-fly-swapped-1-8-and-2-7-p t)
        (require 'xah-fly-keys)
        (xah-fly-keys-set-layout "qwerty") ; required if you use qwerty
        (xah-fly-keys 1)
    )

then restart emacs.

**Comment by antonshwab** [comment] 2017-01-26 22:06
Symbol's function definition is void: xah-fly-set-layout

**Comment by xahlee** [comment] 2017-01-26 22:17
(xah-fly-keys-set-layout "qwerty")

**Comment by antonshwab** [comment] 2017-01-26 22:25
When i edit not lisp (init.vim for example) ";" is working. But with clojure-mode doesn't.

**Comment by xahlee** [comment] 2017-01-26 23:31
i still cannot reproduce.

are you sure you don't have other minor mode? paredit or smartparen?

M-x describe-mode and paste the first section.

**Comment by antonshwab** [comment] 2017-01-27 01:03
Oh, Yes. I off paredit and `;` work now. But how i will edit clojure code?) 
May be you say the convenient way (plugin, mode) to work with brackets?

And please say how I can yank from terminal emacsclient to OS clipboard?
From OS to emacsclient is clear: Cmd-V, but Cmd-C to other way don't work.

**Comment by antonshwab** [comment] 2017-01-27 02:06
[Problem with clipboard fix with this](https://github.com/syl20bnr/spacemacs/issues/2222)

More precisely 
```
(defun dotspacemacs/user-config ()

    ; ...

    (defun copy-to-clipboard ()
      "Copies selection to x-clipboard."
      (interactive)
      (if (display-graphic-p)
          (progn
            (message "Yanked region to x-clipboard!")
            (call-interactively 'clipboard-kill-ring-save)
            )
        (if (region-active-p)
            (progn
              (shell-command-on-region (region-beginning) (region-end) "pbcopy")
              (message "Yanked region to clipboard!")
              (deactivate-mark))
          (message "No region active; can't yank to clipboard!")))
      )

    (defun paste-from-clipboard ()
      "Pastes from x-clipboard."
      (interactive)
      (if (display-graphic-p)
          (progn
            (clipboard-yank)
            (message "graphics active")
            )
        (insert (shell-command-to-string "pbpaste"))
        )
      )
  (evil-leader/set-key "o y" 'copy-to-clipboard)
  (evil-leader/set-key "o p" 'paste-from-clipboard)
)
```

Why was it decided in `xah-fly-command-mode` `x` assign to copy and `c` to smart cut? On the contrary it is more logical. How do you think?

**Comment by xahlee** [comment] 2017-01-27 03:32
here's a quick comment first, regording the semicolon bug and paredit.

i reproduced the problem with paredit. It overrides the semicolon key.

solution is to move xah-fly-keys in minor-mode-map-alist to the front, before paredit.

you can do that manually by elisp code, or, i think loading xah-fly-keys after paredit mode would work.

i'd give you the elisp code, but i don't have it yet.

---------------------------

secondly, i do not recommend paredit. I'm 70% confident that if you use xah-fly-keys with xah-elisp-mode, it's scientifically verifiable it's more efficient that with paredit. That is, assume we can do massive statistical testing, measuring people's lisp editing sessions and keystrokes, and xah-fly-keys + xah-elisp-mode is less keystrokes, and easier fingers, and or faster (require less brain cycle).

now, for editing clojure, i have xah-clojure-mode. it's beta, but i've been using it for 6 months when doing clojure. You could try it.

in the end, i think what you can do this:

1. make xah-fly-keys have more priority than paredit. by editing minor-mode-map-alist or load it later. (i'll have code soon.)

2. try not use paredit, and master xah-fly-keys. May also try xah-clojure-mode for a day and see if it works for you. (i'd improve xah-clojure-mode but lack funding. if you really try to use it and start bug reports, i'll follow thru.)

**Comment by xahlee** [comment] 2017-01-27 03:36
regarding why the copy cut paste are swapped from traditional x c.

the reason was, cut is much more frequently used command. Particularly in xah-fly-keys, it is use to delete current line. So, cut is middle finger, and copy is the weaker ring finger.

the decision isn't solidly final. Because there's a strong impetus from tradition, so the swapping may be quite counter-intuitive.

if after a month, you really feel they shouldn't be swapped, then i'd rethink.

**Comment by xahlee** [comment] 2017-01-27 03:42
here's a tip of using xah-fly-keys sans paredit.

use xah-backward-left-bracket and xah-forward-right-bracket extensively. (on qwerty it's m and .)
and use xah-extend-selection (key 8) extensively. Then use xah-cut-line-or-region (qwerty c). And also xah-delete-backward-char-or-bracket-text (qwerty e). These allows you to manipulate sexp by unit.

to insert paired brackets, use xah-insert-paren. (qwerty space d k in command mode)

the benefit of xah-elisp-mode and xah-clojure-mode is that TAB will format whole sexp.
xah-elisp-mode provides extensive abbrev and template. xah-clojure-mode should be same, but much less templates (that's why it's beta).

**Comment by xahlee** [comment] 2017-01-27 03:44
about fixing copy/paste between OS and emacs, i think the code there is too much.

maybe check this
Emacs: Sync Copy/Paste Clipboards with Linux X11
http://ergoemacs.org/emacs/emacs_x11_sync_clipboard.html
should be just 2 lines of code.

**Comment by xahlee** [comment] 2017-01-27 10:06
this should solve the paredit key override problem.

just eval this, or place anywhere in your init.

    (add-to-list 'emulation-mode-map-alists (list (cons 'xah-fly-keys xah-fly-key-map )))

I wait for a few days for myself to test, and will put this into the mode.

**Comment by antonshwab** [comment] 2017-01-27 12:31
1) Your words are reasonable. I'll try your emacs and clojure mode. Xah-fly-keys is really awesome editing way. 

2) Your copy/paste  fixing don't work for me. I feel that this 
```
(defun copy-to-clipboard ()
  "Copies selection to x-clipboard."
  (interactive)
  (if (display-graphic-p)
      (progn
        (message "Yanked region to x-clipboard!")
        (call-interactively 'clipboard-kill-ring-save)
        )
    (if (region-active-p)
        (progn
          (shell-command-on-region (region-beginning) (region-end) "pbcopy")
          (message "Yanked region to clipboard!")
          (deactivate-mark))
      (message "No region active; can't yank to clipboard!")))
  )
```
 is enough now.

3) I've been thinking about `xah-fly-command-mode-activate`, how make it more conveniently for me. Now try  `(global-set-key (kbd "TAB") 'xah-fly-command-mode-activate)` and it is really suitable for my hands and my keyboard, now. And when i want to insert `indent` - just press `Space-TAB-TAB`. Manually indentation is not often operation, right? Or maybe `indent-for-tab-command` bind to `C-i`. What do you think?

4) I try to solve my problem with the cursor's resistance to change according to mode (command/insert), but unsuccessfully. iTerm2 does not allow `emacsclient -nw` change cursor behavior.  If you decide help me or hint then may be [this help you](https://github.com/7696122/evil-terminal-cursor-changer/blob/master/evil-terminal-cursor-changer.el).
Now i do this workaround: 
```
  (defun insert-message () (message "INSERT!"))
  (add-hook 'xah-fly-insert-mode-activate-hook 'insert-message)
```

**Comment by antonshwab** [comment] 2017-01-27 13:00
I think [expand-region](https://github.com/magnars/expand-region.el) work a little predictable than `8 in command mode`. How I can binding `expand-region` to `8 in command mode`?

**Comment by xahlee** [comment] 2017-01-27 20:39
about using tab key for xah-fly-command-mode-activate,

just beware that tab is used frequently by many 
programing language 
major modes, and in xah elisp mode (or other my major modes), it is used for completion/template expansion and also for indenting whole sexp or {blocks} of code. So, it is one of the top frequently used command.

for emacs major modes, the indentation and its key is fairly complex... (because the command typically bound to tab key is indent-for-tab-command, whose behavior depends on few variables, and especially indent-line-function, which is a variable that calls the “real” command to do indentation...)

so, the bottom line is that if you bind tab key for xah-fly-command-mode-activate, you may have problem config other major modes for indentation. (some other top packages also depends on the default, such as company, auto complete, yasnippet.)

the 【Space Tab …】 key sequence in xah-fly-keys is currently experimental. Basically, i almost never use it. It's a leader key, and many of the command are just dumped there. It is a nice key spot, but i haven't decided what to put there.

**Comment by xahlee** [comment] 2017-01-27 20:55
about fixing cursor shape change for iterm2,

the solution here
https://github.com/7696122/evil-terminal-cursor-changer/blob/master/evil-terminal-cursor-changer.el
seems too hacky trying to solve a problem that isn't meant to be solved.

for now, perhaps a simple solution of changing cursor color, or background color. These are easily doable. 

here's few things that's easy to change.

(set-background-color "honeydew")
(set-background-color "white")

(blink-cursor-mode 0)
(blink-cursor-mode 1)

(global-hl-line-mode 1)
(global-hl-line-mode 0)

I'd consider change part of modeline color.

I would be interest to see which one of the above would work best, but low priority.
Would you open a new bug report for it? that makes it trackable.

**Comment by xahlee** [comment] 2017-01-27 21:10
about expand region,

the command xah-extend-selection is still improving. I'm expanding it's functionality.
But, what's solid for now is that if cursor is on a parenthesis or any type of brackt, it expand to outer ones reliably, in any major mode.

the expand-region package is nice. I've used it for a year, but stopped because felt too slow and big when outside of lisp.

if you want to use it, you can:

    (defalias 'xah-extend-selection 'expand-region)

or, fork xah-fly-keys, in your copy, look for the line
    ("8" . xah-extend-selection)
then just replace it.
also, you could also change keys 7 9 to be expand-region related command.

let's make separate bug report per issue.

**Comment by xahlee** [comment] 2017-01-27 21:16
closing this issue for the key 7 8. Please make new other issue as discussed.

**Comment by antonshwab** [comment] 2017-01-27 23:06
You've been very helpful, thanks.

**Closed** 2017-01-28 04:10 UTC
